export default [
    {
        name:'download',
        path:'/download',
        component:()=>import('@/components/Download'),
    },
    {
        name:'home',
        path:'/home',
        component:()=>import('@/components/Home'),
        children:[
            {
                path:'discover',
                component:()=>import('@/components/Home/Discover'),
            },
            {
                path:'toplist/:id?',
                component:()=>import('@/components/Home/TopList'),
            },
            {
                path:'playlist',
                component:()=>import('@/components/Home/PlayList'),
            },
            {
                path:'djradio',
                component:()=>import('@/components/Home/DjRadio'),
            },
            {
                path:'artist',
                component:()=>import('@/components/Home/Artist'),
            },
            {
                path:'album',
                component:()=>import('@/components/Home/Album'),
            },
        ],
    },
    {
        name:'mymusic',
        path:'/mymusic',
        component:()=>import('@/components/MyMusic'),
        children:[
            {
                path:'playlist',
                component:()=>import('@/components/MyMusic/Logged/Playlist'),
            }
        ]
    },
    {
        name:'friend',
        path:'/friend',
        component:()=>import('@/components/Friend'),
    },
    {
        name:'user',
        path:'/user',
        component:()=>import('@/components/User'),
        children:[
            {
                path:'home',
                component:()=>import('@/components/User/Home'),
            },
            {
                path:'level',
                component:()=>import('@/components/User/Level'),
            }
        ]
    },
    {
        name:'playlist',
        path:'/playlist/:key?',
        component:()=>import('@/components/PlayList'),
    },
    {
        name:'search',
        path:'/search',
        component:()=>import('@/components/Search'),
    },
    {
        name:'song',
        path:'/song',
        component:()=>import("@/components/Song"),
    },
    {
        name:'artist',
        path:'/artist',
        component:()=>import('@/components/Artist'),
        children:[
            {
                path:'song',
                component:()=>import('@/components/Artist/MainerLeft/Song'),
            },
            {
                path:'album',
                component:()=>import('@/components/Artist/MainerLeft/Album'),
            },
            {
                path:'mv',
                component:()=>import('@/components/Artist/MainerLeft/Mv'),
            },
            {
                path:'desc',
                component:()=>import('@/components/Artist/MainerLeft/Desc'),
            },
        ]
    },
    {
        name:'album',
        path:'/album',
        component:()=>import('@/components/Album'),
    },
    //重定向    
    {
        path:'*',
        redirect:'/home/discover'
    },
]